### PR TITLE
Add ja localization

### PR DESCRIPTION
**Pull request by Hallkun19**
Added Japanese folders and files.
Please note that I have only finished up to settings-gameplay.json so far.
Japanese translations will be added from time to time.

P.S.
I’m not very familiar with using GitHub, so I apologize if I made any mistakes.

### CODE REVIEW

**Comment by flustix** [comment]
Could you remove the files and fields that have not been translated yet?

**Comment by Hallkun19** [comment]
I believe I have fixed the issue! Please let me know if there's anything else that needs to be addressed!

**Comment by flustix** [comment]
You, uh, deleted the entire project.

**Comment by flustix** [comment]
I think making a new PR would be easier now.

**Comment by Hallkun19** [comment]
Sorry, should I have only removed the untranslated files in fluXis.Resources/Localization/ja?

**Comment by Hallkun19** [comment]
> I think making a new PR would be easier now.

Okay

**Comment by flustix** [comment]
> Sorry, should I have only removed the untranslated files in fluXis.Resources/Localization/ja?

...Yes.

**Comment by flustix** [comment]
Please try making a new pull request that only adds the strings for actually translated stuff.

**Comment by Hallkun19** [comment]
I'm so sorry... :'-(

**Pull request closed without merging**
